# JVM memory for Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
# AndroidX
android.useAndroidX=true
# Non-transitive R classes keep builds fast and small
android.nonTransitiveRClass=true
# Kotlin code style
kotlin.code.style=official
# Enable configuration cache
org.gradle.configuration-cache=true
